# Generated by Django 6.0.5 on 2026-06-05 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0011_productimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'price'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
